# ============================================================
# MULTI-AGENT STATUS WATCHER
# ============================================================
# Monitors status.md files in modules/ folder and notifies
# Tech Lead when workers complete their tasks.
#
# Usage: .\watcher.ps1
# Stop:  Ctrl+C
# ============================================================

param(
    [string]$ProjectRoot = (Split-Path -Parent $PSScriptRoot),
    [int]$PollIntervalSeconds = 5
)

# Colors for console output
$Colors = @{
    Info    = "Cyan"
    Success = "Green"
    Warning = "Yellow"
    Error   = "Red"
    Status  = "Magenta"
}

function Write-Log {
    param([string]$Message, [string]$Level = "Info")
    $timestamp = Get-Date -Format "HH:mm:ss"
    $color = $Colors[$Level]
    Write-Host "[$timestamp] " -NoNewline -ForegroundColor DarkGray
    Write-Host $Message -ForegroundColor $color
}

function Get-ModuleStatus {
    param([string]$StatusFilePath)
    
    if (-not (Test-Path $StatusFilePath)) {
        return @{ Status = "NO_STATUS_FILE"; Progress = 0 }
    }
    
    $content = Get-Content $StatusFilePath -Raw -ErrorAction SilentlyContinue
    if (-not $content) {
        return @{ Status = "EMPTY"; Progress = 0 }
    }
    
    # Parse status from markdown
    $status = "UNKNOWN"
    $progress = 0
    
    # Look for status patterns
    if ($content -match "Status[:\s]*\*{0,2}(COMPLETED|DONE|FINISHED)\*{0,2}") {
        $status = "COMPLETED"
        $progress = 100
    }
    elseif ($content -match "Status[:\s]*\*{0,2}(IN[_\s]?PROGRESS|WORKING|IMPLEMENTING)\*{0,2}") {
        $status = "IN_PROGRESS"
        # Try to extract progress percentage
        if ($content -match "(\d{1,3})%") {
            $progress = [int]$Matches[1]
        } else {
            $progress = 50
        }
    }
    elseif ($content -match "Status[:\s]*\*{0,2}(PENDING|TODO|NOT[_\s]?STARTED)\*{0,2}") {
        $status = "PENDING"
        $progress = 0
    }
    elseif ($content -match "Status[:\s]*\*{0,2}(BLOCKED|ERROR|FAILED)\*{0,2}") {
        $status = "BLOCKED"
        $progress = -1
    }
    elseif ($content -match "Status[:\s]*\*{0,2}(REVIEW|NEEDS[_\s]?REVIEW)\*{0,2}") {
        $status = "NEEDS_REVIEW"
        $progress = 100
    }
    
    return @{ Status = $status; Progress = $progress; Content = $content }
}

function Update-NotificationsFile {
    param(
        [string]$ModuleName,
        [string]$OldStatus,
        [string]$NewStatus,
        [string]$NotificationsPath
    )
    
    $timestamp = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
    $entry = "| $timestamp | ``$ModuleName`` | $OldStatus -> **$NewStatus** |"
    
    # Create or update notifications file
    if (-not (Test-Path $NotificationsPath)) {
        $header = @"
# Agent Notifications

> Auto-generated by watcher.ps1 - Do not edit manually

| Timestamp | Module | Status Change |
|-----------|--------|---------------|
"@
        Set-Content -Path $NotificationsPath -Value $header -Encoding UTF8
    }
    
    # Append new entry
    Add-Content -Path $NotificationsPath -Value $entry -Encoding UTF8
}

function Update-DashboardFile {
    param(
        [hashtable]$ModuleStatuses,
        [string]$DashboardPath
    )
    
    $timestamp = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
    
    $content = @"
# Module Status Dashboard

> Last updated: $timestamp
> Auto-generated by watcher.ps1

## Overview

| Module | Status | Progress |
|--------|--------|----------|
"@
    
    $completed = 0
    $inProgress = 0
    $pending = 0
    $blocked = 0
    
    foreach ($module in $ModuleStatuses.Keys | Sort-Object) {
        $info = $ModuleStatuses[$module]
        $statusIcon = switch ($info.Status) {
            "COMPLETED"    { "[OK]" }
            "IN_PROGRESS"  { "[..]" }
            "PENDING"      { "[  ]" }
            "BLOCKED"      { "[!!]" }
            "NEEDS_REVIEW" { "[??]" }
            default        { "[--]" }
        }
        
        $progressBar = if ($info.Progress -ge 0) {
            $filled = [math]::Floor($info.Progress / 10)
            $empty = 10 - $filled
            "[" + ("#" * $filled) + ("-" * $empty) + "] $($info.Progress)%"
        } else {
            "N/A"
        }
        
        $content += "| ``$module`` | $statusIcon $($info.Status) | $progressBar |`n"
        
        switch ($info.Status) {
            "COMPLETED"    { $completed++ }
            "IN_PROGRESS"  { $inProgress++ }
            "PENDING"      { $pending++ }
            "BLOCKED"      { $blocked++ }
        }
    }
    
    $total = $ModuleStatuses.Count
    $content += @"

## Summary

- **Total Modules**: $total
- [OK] **Completed**: $completed
- [..] **In Progress**: $inProgress
- [  ] **Pending**: $pending
- [!!] **Blocked**: $blocked

---

> TIP: Run ``Get-Content dashboard.md -Wait`` in another terminal for live updates
"@
    
    Set-Content -Path $DashboardPath -Value $content -Encoding UTF8
}

# ============================================================
# MAIN LOOP
# ============================================================

Clear-Host
Write-Host ""
Write-Host "  =========================================" -ForegroundColor Cyan
Write-Host "       MULTI-AGENT STATUS WATCHER         " -ForegroundColor Cyan
Write-Host "  =========================================" -ForegroundColor Cyan
Write-Host ""
Write-Host "  Monitoring: modules/*/status.md" -ForegroundColor White
Write-Host "  Interval:   $PollIntervalSeconds seconds" -ForegroundColor White
Write-Host "  Press Ctrl+C to stop" -ForegroundColor DarkGray
Write-Host ""

$modulesPath = Join-Path $ProjectRoot "modules"
$notificationsPath = Join-Path $ProjectRoot "notifications.md"
$dashboardPath = Join-Path $ProjectRoot "dashboard.md"

if (-not (Test-Path $modulesPath)) {
    Write-Log "Modules folder not found: $modulesPath" "Error"
    exit 1
}

Write-Log "Project Root: $ProjectRoot" "Info"
Write-Log "Watching: $modulesPath" "Info"
Write-Host ""

# Store previous states
$previousStates = @{}

# Initial scan
$modules = Get-ChildItem -Path $modulesPath -Directory | Where-Object { $_.Name -ne "_template" }
foreach ($module in $modules) {
    $statusFile = Join-Path $module.FullName "status.md"
    $statusInfo = Get-ModuleStatus -StatusFilePath $statusFile
    $previousStates[$module.Name] = $statusInfo.Status
    Write-Log "Found module: $($module.Name) - $($statusInfo.Status)" "Status"
}

Write-Host ""
Write-Log "Initial scan complete. Starting watch loop..." "Success"
Write-Host ""

try {
    while ($true) {
        $currentStatuses = @{}
        $modules = Get-ChildItem -Path $modulesPath -Directory | Where-Object { $_.Name -ne "_template" }
        
        foreach ($module in $modules) {
            $statusFile = Join-Path $module.FullName "status.md"
            $statusInfo = Get-ModuleStatus -StatusFilePath $statusFile
            $currentStatuses[$module.Name] = $statusInfo
            
            $prevStatus = $previousStates[$module.Name]
            $newStatus = $statusInfo.Status
            
            # Detect new modules
            if (-not $prevStatus) {
                Write-Log "[NEW] New module detected: $($module.Name)" "Warning"
                $previousStates[$module.Name] = $newStatus
                continue
            }
            
            # Detect status changes
            if ($prevStatus -ne $newStatus) {
                Write-Log "[CHANGE] $($module.Name): $prevStatus -> $newStatus" "Success"
                
                # Update notifications file
                Update-NotificationsFile -ModuleName $module.Name -OldStatus $prevStatus -NewStatus $newStatus -NotificationsPath $notificationsPath
                
                if ($newStatus -eq "BLOCKED") {
                    Write-Log "[ALERT] Module $($module.Name) is BLOCKED! Check status.md for details." "Warning"
                }
                
                $previousStates[$module.Name] = $newStatus
            }
        }
        
        # Update dashboard
        Update-DashboardFile -ModuleStatuses $currentStatuses -DashboardPath $dashboardPath
        
        Start-Sleep -Seconds $PollIntervalSeconds
    }
}
finally {
    Write-Host ""
    Write-Log "Watcher stopped." "Warning"
}
